version: '3.6'
services:
  graphql-engine-qor:
    image: hasura/graphql-engine:v1.3.0
    ports:
    - "8088:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:123456@192.168.111.147:5432/qor
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## HASURA_GRAPHQL_ADMIN_SECRET: admin
